// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLMtFahGVpUj_QbfVdAzSDEw5qVxYy-3g',
    appId: '1:67040239035:web:7c255b36ea066bbf8bb89e',
    messagingSenderId: '67040239035',
    projectId: 'sso-demo-flutter',
    authDomain: 'sso-demo-flutter.firebaseapp.com',
    storageBucket: 'sso-demo-flutter.appspot.com',
    measurementId: 'G-BMEM7CT3R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC23Kg89pWlIW7dR7tqG-QgMvozel_iUZ4',
    appId: '1:67040239035:android:078b2160d2ea29ae8bb89e',
    messagingSenderId: '67040239035',
    projectId: 'sso-demo-flutter',
    storageBucket: 'sso-demo-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr2toV8yWtoxyu47jVaFZafQfQZoExofM',
    appId: '1:67040239035:ios:bd24153e18b5d1c28bb89e',
    messagingSenderId: '67040239035',
    projectId: 'sso-demo-flutter',
    storageBucket: 'sso-demo-flutter.appspot.com',
    androidClientId: '67040239035-le95ve5rkfnifmtq79n216okpec2j2sv.apps.googleusercontent.com',
    iosClientId: '67040239035-n8s9idaqei781jbdqu2p5ur9ii8e80ue.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocAnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr2toV8yWtoxyu47jVaFZafQfQZoExofM',
    appId: '1:67040239035:ios:bd24153e18b5d1c28bb89e',
    messagingSenderId: '67040239035',
    projectId: 'sso-demo-flutter',
    storageBucket: 'sso-demo-flutter.appspot.com',
    androidClientId: '67040239035-le95ve5rkfnifmtq79n216okpec2j2sv.apps.googleusercontent.com',
    iosClientId: '67040239035-n8s9idaqei781jbdqu2p5ur9ii8e80ue.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocAnd',
  );
}
